version: "3.7"

services:
    elastic:
        container_name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        restart: on-failure
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        ulimits:
            memlock:
                soft: -1
                hard: -1

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.12.0
        restart: on-failure
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elastic:9200
            ELASTICSEARCH_HOSTS: http://elastic:9200

    indexer:
        container_name: indexer
        build:
            dockerfile: docker/indexer/Dockerfile
            context: backend
        volumes:
            - gomodules:/go/pkg/mod
            - ./backend:/go/pkg/app

    search:
        container_name: search
        build:
            dockerfile: docker/search/Dockerfile
            context: backend
        ports:
            - 8081:80
        volumes:
            - gomodules:/go/pkg/mod
            - ./backend:/go/pkg/app

    frontend:
        container_name: frontend
        build:
            dockerfile: docker/Dockerfile
            context: frontend
        ports:
            - 8080:8080
        volumes:
            - ./frontend:/app

volumes:
    esdata:
    gomodules:
